"""initial schema

Revision ID: 66f2af9aa07a
Revises: 
Create Date: 2026-06-09 22:03:19.913018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66f2af9aa07a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cuisine_type', sa.String(length=100), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Extensible config: opening hours, address, tax rate, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_restaurant', 'menu_categories', ['restaurant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending | confirmed | in_kitchen | ready | completed | cancelled'),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Auto-maintained by DB trigger on order_items changes'),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_session_id'), 'orders', ['session_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="e.g. ['vegetarian', 'spicy', 'gluten-free']"),
    sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="[{name: 'Size', options: ['S','L'], price_delta: [0, 2.0]}]"),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True, comment='Generated by trigger: to_tsvector(name || description || tags)'),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_item_available', 'menu_items', ['restaurant_id', 'is_available'], unique=False)
    op.create_index('idx_item_fts', 'menu_items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_item_name_trgm', 'menu_items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_item_restaurant', 'menu_items', ['restaurant_id'], unique=False)
    op.create_index('idx_item_tags', 'menu_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('modifiers_chosen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Auto-computed: price_snapshot * quantity (maintained by trigger)'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_item_order', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_item_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_item_tags', table_name='menu_items', postgresql_using='gin')
    op.drop_index('idx_item_restaurant', table_name='menu_items')
    op.drop_index('idx_item_name_trgm', table_name='menu_items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_item_fts', table_name='menu_items', postgresql_using='gin')
    op.drop_index('idx_item_available', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_orders_session_id'), table_name='orders')
    op.drop_index('idx_order_restaurant_status', table_name='orders')
    op.drop_index('idx_order_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_category_restaurant', table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
