"""add_feature_columns_v2

Revision ID: 9c2ca1db7747
Revises: 66f2af9aa07a
Create Date: 2026-06-10 13:36:28.710140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c2ca1db7747'
down_revision: Union[str, Sequence[str], None] = '66f2af9aa07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('dietary_restrictions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('allergens', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('strict_allergens', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('order_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('applies_to_ids', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=50), nullable=False),
    sa.Column('applies_to_ids', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('valid_days', postgresql.ARRAY(sa.Integer()), server_default='{0,1,2,3,4,5,6}', nullable=False),
    sa.Column('valid_from', sa.Time(), nullable=True),
    sa.Column('valid_until', sa.Time(), nullable=True),
    sa.Column('valid_date_from', sa.Date(), nullable=True),
    sa.Column('valid_date_until', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_affinity',
    sa.Column('item_a_id', sa.Integer(), nullable=False),
    sa.Column('item_b_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('co_occurrence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lift_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('last_computed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_a_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_b_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_a_id', 'item_b_id')
    )
    op.add_column('menu_items', sa.Column('ingredients', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('menu_items', sa.Column('allergens', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('menu_items', sa.Column('nutrition_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('menu_items', sa.Column('allowed_modifications', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('menu_items', sa.Column('available_during', postgresql.TSTZRANGE(), nullable=True))
    op.add_column('menu_items', sa.Column('available_days', postgresql.ARRAY(sa.Integer()), server_default='{0,1,2,3,4,5,6}', nullable=True))
    op.add_column('menu_items', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('menu_items', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('display_order', sa.Integer(), server_default='0', nullable=True))
    op.add_column('menu_items', sa.Column('has_gluten', sa.Boolean(), server_default=sa.FetchedValue(), nullable=True))
    op.add_column('menu_items', sa.Column('has_dairy', sa.Boolean(), server_default=sa.FetchedValue(), nullable=True))
    op.add_column('menu_items', sa.Column('has_nuts', sa.Boolean(), server_default=sa.FetchedValue(), nullable=True))
    op.add_column('menu_items', sa.Column('has_shellfish', sa.Boolean(), server_default=sa.FetchedValue(), nullable=True))
    op.create_index('idx_items_allergens', 'menu_items', ['allergens'], unique=False, postgresql_using='gin')
    op.create_index('idx_items_available', 'menu_items', ['available_days'], unique=False, postgresql_using='gin')
    op.create_index('idx_items_ingredients', 'menu_items', ['ingredients'], unique=False, postgresql_using='gin')
    op.add_column('order_items', sa.Column('modifications_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order_items', sa.Column('allergen_warnings', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('order_items', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('added_by', sa.Text(), nullable=True))
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Auto-computed by trigger',
               existing_comment='Auto-computed: price_snapshot * quantity (maintained by trigger)',
               existing_nullable=False)
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('language_code', sa.String(length=10), server_default='en', nullable=True))
    op.add_column('orders', sa.Column('discount_total', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True))
    op.add_column('orders', sa.Column('promotions_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_orders_customer_phone', 'orders', ['customer_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_orders_customer_phone', table_name='orders')
    op.drop_column('orders', 'promotions_applied')
    op.drop_column('orders', 'discount_total')
    op.drop_column('orders', 'language_code')
    op.drop_column('orders', 'customer_phone')
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Auto-computed: price_snapshot * quantity (maintained by trigger)',
               existing_comment='Auto-computed by trigger',
               existing_nullable=False)
    op.drop_column('order_items', 'added_by')
    op.drop_column('order_items', 'original_price')
    op.drop_column('order_items', 'allergen_warnings')
    op.drop_column('order_items', 'modifications_applied')
    op.drop_index('idx_items_ingredients', table_name='menu_items', postgresql_using='gin')
    op.drop_index('idx_items_available', table_name='menu_items', postgresql_using='gin')
    op.drop_index('idx_items_allergens', table_name='menu_items', postgresql_using='gin')
    op.drop_column('menu_items', 'has_shellfish')
    op.drop_column('menu_items', 'has_nuts')
    op.drop_column('menu_items', 'has_dairy')
    op.drop_column('menu_items', 'has_gluten')
    op.drop_column('menu_items', 'display_order')
    op.drop_column('menu_items', 'available_quantity')
    op.drop_column('menu_items', 'translations')
    op.drop_column('menu_items', 'available_days')
    op.drop_column('menu_items', 'available_during')
    op.drop_column('menu_items', 'allowed_modifications')
    op.drop_column('menu_items', 'nutrition_info')
    op.drop_column('menu_items', 'allergens')
    op.drop_column('menu_items', 'ingredients')
    op.drop_table('item_affinity')
    op.drop_table('price_rules')
    op.drop_table('order_rules')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
