"""add_embedding_columns_intent_table

Revision ID: 9cd33886d71f
Revises: 9c2ca1db7747
Create Date: 2026-06-10 20:24:36.190625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cd33886d71f'
down_revision: Union[str, Sequence[str], None] = '9c2ca1db7747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import pgvector.sqlalchemy
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_code', sa.String(length=60), nullable=False),
    sa.Column('example_query', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_params_hint', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_safety_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('similarity_threshold', sa.Float(), server_default='0.80', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_definitions_intent_code'), 'intent_definitions', ['intent_code'], unique=False)
    op.create_index(op.f('ix_intent_definitions_is_safety_critical'), 'intent_definitions', ['is_safety_critical'], unique=False)
    op.add_column('menu_items', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    import pgvector.sqlalchemy
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'embedding')
    op.drop_index(op.f('ix_intent_definitions_is_safety_critical'), table_name='intent_definitions')
    op.drop_index(op.f('ix_intent_definitions_intent_code'), table_name='intent_definitions')
    op.drop_table('intent_definitions')
    # ### end Alembic commands ###
