from datetime import datetime
from decimal import Decimal
from typing import Optional
from sqlalchemy import (
    Integer, String, Text, Boolean, Numeric, DateTime,
    ForeignKey, Index, func, Time, Date, FetchedValue, Float
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, ARRAY, TSTZRANGE
from pgvector.sqlalchemy import Vector
from db.base import Base


# ─────────────────────────────────────────────────────────────
# RESTAURANTS  (one row per tenant)
# ─────────────────────────────────────────────────────────────
class Restaurant(Base):
    __tablename__ = "restaurants"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    cuisine_type: Mapped[str] = mapped_column(String(100), nullable=False)
    personality: Mapped[str] = mapped_column(Text, nullable=False)
    special_instructions: Mapped[Optional[str]] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict,
        comment="Extensible config: opening hours, address, tax rate, etc."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    menu_categories: Mapped[list["MenuCategory"]] = relationship(
        back_populates="restaurant", cascade="all, delete-orphan"
    )
    menu_items: Mapped[list["MenuItem"]] = relationship(
        back_populates="restaurant", cascade="all, delete-orphan"
    )
    orders: Mapped[list["Order"]] = relationship(back_populates="restaurant")


# ─────────────────────────────────────────────────────────────
# MENU CATEGORIES  (Mains, Sides, Drinks, etc.)
# ─────────────────────────────────────────────────────────────
class MenuCategory(Base):
    __tablename__ = "menu_categories"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    display_order: Mapped[int] = mapped_column(Integer, default=0)

    restaurant: Mapped["Restaurant"] = relationship(back_populates="menu_categories")
    items: Mapped[list["MenuItem"]] = relationship(back_populates="category")

    __table_args__ = (
        Index("idx_category_restaurant", "restaurant_id"),
    )


# ─────────────────────────────────────────────────────────────
# MENU ITEMS
# ─────────────────────────────────────────────────────────────
class MenuItem(Base):
    __tablename__ = "menu_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False
    )
    category_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("menu_categories.id", ondelete="SET NULL")
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    is_available: Mapped[bool] = mapped_column(Boolean, default=True)
    tags: Mapped[list] = mapped_column(
        JSONB, default=list,
        comment="e.g. ['vegetarian', 'spicy', 'gluten-free']"
    )
    modifiers: Mapped[list] = mapped_column(
        JSONB, default=list,
        comment="[{name: 'Size', options: ['S','L'], price_delta: [0, 2.0]}]"
    )
    # Full-text search vector — kept in sync by a DB trigger
    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR, nullable=True,
        comment="Generated by trigger: to_tsvector(name || description || tags)"
    )

    # Extended Columns for V2 features (made nullable or Optional)
    ingredients: Mapped[Optional[list[str]]] = mapped_column(ARRAY(String), server_default="{}")
    allergens: Mapped[Optional[list[str]]] = mapped_column(ARRAY(String), server_default="{}")
    nutrition_info: Mapped[Optional[dict]] = mapped_column(JSONB, server_default="{}")
    allowed_modifications: Mapped[Optional[dict]] = mapped_column(JSONB, server_default="{}")
    available_during: Mapped[Optional[str]] = mapped_column(TSTZRANGE, nullable=True)
    available_days: Mapped[Optional[list[int]]] = mapped_column(ARRAY(Integer), server_default="{0,1,2,3,4,5,6}")
    translations: Mapped[Optional[dict]] = mapped_column(JSONB, server_default="{}")
    available_quantity: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    display_order: Mapped[Optional[int]] = mapped_column(Integer, default=0, server_default="0")
    embedding: Mapped[Optional[list[float]]] = mapped_column(Vector(768), nullable=True)

    # Allergen flags generated columns (mapped as read-only)
    has_gluten: Mapped[Optional[bool]] = mapped_column(Boolean, FetchedValue())
    has_dairy: Mapped[Optional[bool]] = mapped_column(Boolean, FetchedValue())
    has_nuts: Mapped[Optional[bool]] = mapped_column(Boolean, FetchedValue())
    has_shellfish: Mapped[Optional[bool]] = mapped_column(Boolean, FetchedValue())

    restaurant: Mapped["Restaurant"] = relationship(back_populates="menu_items")
    category: Mapped[Optional["MenuCategory"]] = relationship(back_populates="items")

    __table_args__ = (
        Index("idx_item_restaurant", "restaurant_id"),
        Index("idx_item_available", "restaurant_id", "is_available"),
        Index("idx_item_fts", "search_vector", postgresql_using="gin"),
        Index("idx_item_name_trgm", "name", postgresql_using="gin",
              postgresql_ops={"name": "gin_trgm_ops"}),
        Index("idx_item_tags", "tags", postgresql_using="gin"),
        Index("idx_items_allergens", "allergens", postgresql_using="gin"),
        Index("idx_items_ingredients", "ingredients", postgresql_using="gin"),
        Index("idx_items_available", "available_days", postgresql_using="gin"),
    )


# ─────────────────────────────────────────────────────────────
# ORDERS
# ─────────────────────────────────────────────────────────────
class Order(Base):
    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id"), nullable=False
    )
    session_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    customer_name: Mapped[Optional[str]] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(
        String(50), default="pending",
        comment="pending | confirmed | in_kitchen | ready | completed | cancelled"
    )
    total: Mapped[Decimal] = mapped_column(
        Numeric(10, 2), default=Decimal("0.00"),
        comment="Auto-maintained by DB trigger on order_items changes"
    )
    payment_method: Mapped[Optional[str]] = mapped_column(String(50))
    notes: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # Extended Columns for V2 features (made nullable or Optional)
    customer_phone: Mapped[Optional[str]] = mapped_column(String(30))
    language_code: Mapped[Optional[str]] = mapped_column(String(10), default="en", server_default="en")
    discount_total: Mapped[Optional[Decimal]] = mapped_column(Numeric(10, 2), default=Decimal("0.00"), server_default="0.00")
    promotions_applied: Mapped[Optional[list]] = mapped_column(JSONB, default=list)

    restaurant: Mapped["Restaurant"] = relationship(back_populates="orders")
    items: Mapped[list["OrderItem"]] = relationship(
        back_populates="order", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_order_restaurant_status", "restaurant_id", "status"),
        Index("idx_order_created", "created_at"),
        Index("idx_orders_customer_phone", "customer_phone"),
    )


# ─────────────────────────────────────────────────────────────
# ORDER ITEMS
# ─────────────────────────────────────────────────────────────
class OrderItem(Base):
    __tablename__ = "order_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False
    )
    menu_item_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("menu_items.id"), nullable=False
    )
    name_snapshot: Mapped[str] = mapped_column(String(200), nullable=False)
    price_snapshot: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, default=1)
    modifiers_chosen: Mapped[dict] = mapped_column(JSONB, default=dict)
    subtotal: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        comment="Auto-computed by trigger"
    )

    # Extended Columns for V2 features
    modifications_applied: Mapped[Optional[dict]] = mapped_column(JSONB, default=dict)
    allergen_warnings: Mapped[Optional[list[str]]] = mapped_column(ARRAY(String), default=list)
    original_price: Mapped[Optional[Decimal]] = mapped_column(Numeric(10, 2))
    added_by: Mapped[Optional[str]] = mapped_column(Text)

    order: Mapped["Order"] = relationship(back_populates="items")

    __table_args__ = (
        Index("idx_order_item_order", "order_id"),
    )


# ─────────────────────────────────────────────────────────────
# PRICE RULES
# ─────────────────────────────────────────────────────────────
class PriceRule(Base):
    __tablename__ = "price_rules"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(Integer, ForeignKey("restaurants.id", ondelete="CASCADE"))
    name: Mapped[str] = mapped_column(String(200))
    label: Mapped[str] = mapped_column(Text)
    description: Mapped[Optional[str]] = mapped_column(Text)
    rule_type: Mapped[str] = mapped_column(String(50))  # 'percentage_off' | 'fixed_off' | 'fixed_price'
    value: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    applies_to: Mapped[str] = mapped_column(String(50))  # 'category' | 'item' | 'order' | 'all'
    applies_to_ids: Mapped[list[int]] = mapped_column(ARRAY(Integer), server_default="{}")
    valid_days: Mapped[list[int]] = mapped_column(ARRAY(Integer), server_default="{0,1,2,3,4,5,6}")
    valid_from: Mapped[Optional[datetime]] = mapped_column(Time)
    valid_until: Mapped[Optional[datetime]] = mapped_column(Time)
    valid_date_from: Mapped[Optional[datetime]] = mapped_column(Date)
    valid_date_until: Mapped[Optional[datetime]] = mapped_column(Date)
    priority: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)


# ─────────────────────────────────────────────────────────────
# ORDER RULES
# ─────────────────────────────────────────────────────────────
class OrderRule(Base):
    __tablename__ = "order_rules"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(Integer, ForeignKey("restaurants.id", ondelete="CASCADE"))
    rule_type: Mapped[str] = mapped_column(String(50))  # 'max_total' | 'min_total' etc.
    value: Mapped[Optional[Decimal]] = mapped_column(Numeric(10, 2))
    value_text: Mapped[Optional[str]] = mapped_column(Text)
    applies_to_ids: Mapped[list[int]] = mapped_column(ARRAY(Integer), server_default="{}")
    description: Mapped[str] = mapped_column(Text)
    error_message: Mapped[Optional[str]] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)


# ─────────────────────────────────────────────────────────────
# CUSTOMER PROFILES
# ─────────────────────────────────────────────────────────────
class CustomerProfile(Base):
    __tablename__ = "customer_profiles"
    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("restaurants.id", ondelete="CASCADE"))
    phone: Mapped[Optional[str]] = mapped_column(String(30), unique=True)
    email: Mapped[Optional[str]] = mapped_column(String(200), unique=True)
    name: Mapped[Optional[str]] = mapped_column(String(200))
    language_code: Mapped[str] = mapped_column(String(10), default="en")
    dietary_restrictions: Mapped[list[str]] = mapped_column(ARRAY(String), server_default="{}")
    allergens: Mapped[list[str]] = mapped_column(ARRAY(String), server_default="{}")
    strict_allergens: Mapped[list[str]] = mapped_column(ARRAY(String), server_default="{}")
    preferences: Mapped[dict] = mapped_column(JSONB, default=dict, server_default="{}")
    total_orders: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    total_spend: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=Decimal("0.00"))
    loyalty_points: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# ─────────────────────────────────────────────────────────────
# ITEM AFFINITY
# ─────────────────────────────────────────────────────────────
class ItemAffinity(Base):
    __tablename__ = "item_affinity"
    item_a_id: Mapped[int] = mapped_column(Integer, ForeignKey("menu_items.id", ondelete="CASCADE"), primary_key=True)
    item_b_id: Mapped[int] = mapped_column(Integer, ForeignKey("menu_items.id", ondelete="CASCADE"), primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(Integer)
    co_occurrence: Mapped[int] = mapped_column(Integer, default=0, server_default="0")
    lift_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(6, 3))
    last_computed: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# ─────────────────────────────────────────────────────────────
# INTENT DEFINITIONS  (pgvector Pre-Dispatch lookup)
# ─────────────────────────────────────────────────────────────
class IntentDefinition(Base):
    __tablename__ = "intent_definitions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    intent_code: Mapped[str] = mapped_column(String(60), nullable=False, index=True)
    example_query: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[Optional[list[float]]] = mapped_column(Vector(768), nullable=True)
    tool_name: Mapped[str] = mapped_column(String(100), nullable=False)
    tool_params_hint: Mapped[dict] = mapped_column(JSONB, server_default="{}", default=dict)
    is_safety_critical: Mapped[bool] = mapped_column(Boolean, default=False, server_default="false", index=True)
    similarity_threshold: Mapped[float] = mapped_column(Float, default=0.80, server_default="0.80")
    priority: Mapped[int] = mapped_column(Integer, default=5, server_default="5")
