from datetime import datetime
from decimal import Decimal
from typing import Optional
from sqlalchemy import (
    Integer, String, Text, Boolean, Numeric, DateTime,
    ForeignKey, Index, func
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from db.base import Base


# ─────────────────────────────────────────────────────────────
# RESTAURANTS  (one row per tenant)
# ─────────────────────────────────────────────────────────────
class Restaurant(Base):
    __tablename__ = "restaurants"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    cuisine_type: Mapped[str] = mapped_column(String(100), nullable=False)
    personality: Mapped[str] = mapped_column(Text, nullable=False)
    special_instructions: Mapped[Optional[str]] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict,
        comment="Extensible config: opening hours, address, tax rate, etc."
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Relationships
    menu_categories: Mapped[list["MenuCategory"]] = relationship(
        back_populates="restaurant", cascade="all, delete-orphan"
    )
    menu_items: Mapped[list["MenuItem"]] = relationship(
        back_populates="restaurant", cascade="all, delete-orphan"
    )
    orders: Mapped[list["Order"]] = relationship(back_populates="restaurant")


# ─────────────────────────────────────────────────────────────
# MENU CATEGORIES  (Mains, Sides, Drinks, etc.)
# ─────────────────────────────────────────────────────────────
class MenuCategory(Base):
    __tablename__ = "menu_categories"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    display_order: Mapped[int] = mapped_column(Integer, default=0)

    restaurant: Mapped["Restaurant"] = relationship(back_populates="menu_categories")
    items: Mapped[list["MenuItem"]] = relationship(back_populates="category")

    __table_args__ = (
        Index("idx_category_restaurant", "restaurant_id"),
    )


# ─────────────────────────────────────────────────────────────
# MENU ITEMS
# ─────────────────────────────────────────────────────────────
class MenuItem(Base):
    __tablename__ = "menu_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id", ondelete="CASCADE"), nullable=False
    )
    category_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("menu_categories.id", ondelete="SET NULL")
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    price: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    is_available: Mapped[bool] = mapped_column(Boolean, default=True)
    tags: Mapped[list] = mapped_column(
        JSONB, default=list,
        comment="e.g. ['vegetarian', 'spicy', 'gluten-free']"
    )
    modifiers: Mapped[list] = mapped_column(
        JSONB, default=list,
        comment="[{name: 'Size', options: ['S','L'], price_delta: [0, 2.0]}]"
    )
    # Full-text search vector — kept in sync by a DB trigger
    search_vector: Mapped[Optional[str]] = mapped_column(
        TSVECTOR, nullable=True,
        comment="Generated by trigger: to_tsvector(name || description || tags)"
    )

    restaurant: Mapped["Restaurant"] = relationship(back_populates="menu_items")
    category: Mapped[Optional["MenuCategory"]] = relationship(back_populates="items")

    __table_args__ = (
        Index("idx_item_restaurant", "restaurant_id"),
        Index("idx_item_available", "restaurant_id", "is_available"),
        Index("idx_item_fts", "search_vector", postgresql_using="gin"),
        Index("idx_item_name_trgm", "name", postgresql_using="gin",
              postgresql_ops={"name": "gin_trgm_ops"}),
        Index("idx_item_tags", "tags", postgresql_using="gin"),
    )


# ─────────────────────────────────────────────────────────────
# ORDERS
# ─────────────────────────────────────────────────────────────
class Order(Base):
    __tablename__ = "orders"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    restaurant_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("restaurants.id"), nullable=False
    )
    session_id: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    customer_name: Mapped[Optional[str]] = mapped_column(String(200))
    status: Mapped[str] = mapped_column(
        String(50), default="pending",
        comment="pending | confirmed | in_kitchen | ready | completed | cancelled"
    )
    total: Mapped[Decimal] = mapped_column(
        Numeric(10, 2), default=Decimal("0.00"),
        comment="Auto-maintained by DB trigger on order_items changes"
    )
    payment_method: Mapped[Optional[str]] = mapped_column(String(50))
    notes: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    restaurant: Mapped["Restaurant"] = relationship(back_populates="orders")
    items: Mapped[list["OrderItem"]] = relationship(
        back_populates="order", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("idx_order_restaurant_status", "restaurant_id", "status"),
        Index("idx_order_created", "created_at"),
    )


# ─────────────────────────────────────────────────────────────
# ORDER ITEMS  (price_snapshot = price frozen at order time)
# ─────────────────────────────────────────────────────────────
class OrderItem(Base):
    __tablename__ = "order_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    order_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False
    )
    menu_item_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("menu_items.id"), nullable=False
    )
    # ── PRICE INTEGRITY: always snapshot at time of order ──
    name_snapshot: Mapped[str] = mapped_column(String(200), nullable=False)
    price_snapshot: Mapped[Decimal] = mapped_column(Numeric(10, 2), nullable=False)
    quantity: Mapped[int] = mapped_column(Integer, default=1)
    modifiers_chosen: Mapped[dict] = mapped_column(JSONB, default=dict)
    subtotal: Mapped[Decimal] = mapped_column(
        Numeric(10, 2),
        comment="Auto-computed: price_snapshot * quantity (maintained by trigger)"
    )

    order: Mapped["Order"] = relationship(back_populates="items")

    __table_args__ = (
        Index("idx_order_item_order", "order_id"),
    )
